# title: "Reading and Writing YAML to a File in Node.js/JavaScript"
# url path: "/reading-and-writing-yaml-to-a-file-in-node-js-javascript"
# domain: "stackabuse.com"
# port: 443
# is-https: true
# meta:
#   published-at: "Nov. 1st, 2019"
#   author:
#     name: "Scott Robinson"
#     contact: "scott@stackabuse.com"
#   tags:
#     - javascript
#     - node.js
#     - web development
commands:
  misc:
    # 2048: 2048 명령어 이다.
    # covid: covid 명령어 이다.
    # dice: dice 명령어 이다.
    embed_ex: embed_ex 명령어 이다.
    embed_ex2: embed_ex2 명령어 이다.
    help: help 명령어 이다.
    ping: ping 명령어 이다.
    random: random 명령어 이다.
    serverinfo: serverinfo 명령어 이다.
    serverinfo_v12: serverinfo_v12 명령어 이다.
    typing: typing 명령어 이다.
    userinfo: userinfo 명령어 이다.
    userinfo2: userinfo2 명령어 이다.
  mod:
    addRole: addRole 명령어 이다.
    ban: ban 명령어 이다.
    emojiRole: emojiRole 명령어 이다.
    kick: kick 명령어 이다.
    mute: mute 명령어 이다.
    purge: purge 명령어 이다.
    removeRole: removeRole 명령어 이다.
    unban: unban 명령어 이다.
    unmute: unmute 명령어 이다.
